on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso para instalar Java (versión 17) con la distribución Temurin
      - name: Install Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version
    
      # Paso para instalar dependencias de Node.js
      - name: Install Node.js dependencies
        run: |
          npm install
          
      # Paso para ejecutar el análisis de SonarQube
      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v3.0.0 
        with: 
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=api-js-app
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
